### ISSUE TITLE
error when starting the game via launcher.exe

### ISSUE THREAD

**Issue by JimG1** [DeadlySurprise/FO2-Splitscreen#7] opened 2017-12-30 15:03 UTC
Hello, when starting the game via launcher.exe, I get an error : Unhandled exception in 0x73e812f9! Error Code :0xc0000005

If you do not understand something, forgive me since I'm from Ukraine and translate it via google translate

**Comment by MorMund** [comment] 2018-01-02 20:45
Possible duplicate of #3 
Can you try with the [new version](https://github.com/DeadlySurprise/FO2-Splitscreen/releases)?

**Comment by JimG1** [comment] 2018-01-02 20:58
I downloaded a new release, and now generally when you click Launch nothing happens.

In short, like I ran the game (kicked the old release) and one client started and gave another error: Unhandled exception at 0x68bb12f9! Error code: 0xc0000005

Fuck, it almost starts there when on the client that joins when the button is clicked the client is ready to crash with this error: Unhandled exceptin at 0x5bfe49!

**Comment by JimG1** [comment] 2018-01-02 21:03
In short, like I ran the game (kicked the old release) and one client started and gave another error: Unhandled exception at 0x68bb12f9! Error code: 0xc0000005

**Comment by JimG1** [comment] 2018-01-02 21:09
Fuck, it almost starts there when on the client that joins when the button is clicked the client is ready to crash with this error: Unhandled exceptin at 0x5bfe49!

**Comment by MorMund** [comment] 2018-01-02 21:29
Please use the edit function to add new information to your comments.

Can you confirm that the new version (0.1.1) does not launch at all?
If so can you try with [this version](https://mega.nz/#!QJcQCIKB!Keg3tAIsIU-QAlO7f9G7y1ZkNTKxuETocWLE_iS6X6c) instead?

**Comment by JimG1** [comment] 2018-01-02 21:35
https://imgur.com/Af7U4vn

https://imgur.com/jt0Qa1I

it's not launching



but after launching through the launcher
https://imgur.com/LsTbZcG

it's version 0.1.1

**Comment by MorMund** [comment] 2018-01-03 10:52
The launcher not working is a duplicate of #9.

**Closed as completed by MorMund** 2018-01-03 10:52 UTC
Labels: bug, duplicate
